//
//  DetailWorker.swift
//  TheMovieDb
//
//  Created by Misael Chávez on 30/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailWorker {
    func getImage(posterURL: URL?, completionHandler: @escaping (UIImage) -> Void) {
        if let posterURL = posterURL {
            ImageDownloader.getImage(withURL: posterURL) { image in
                if let image = image {
                    completionHandler(image)
                }
            }
        }
    }
}
