//
//  DetailInteractor.swift
//  TheMovieDb
//
//  Created by Misael Chávez on 30/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic {
    func doLoadMovieData(request: Detail.Movie.Request)
}

protocol DetailDataStore {
    var movieViewModel: MovieViewModel { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore {
    var movieViewModel: MovieViewModel
    
    init(movieViewModel: MovieViewModel) {
        self.movieViewModel = movieViewModel
    }
    
    var presenter: DetailPresentationLogic?
    var worker: DetailWorker?
    
    // MARK: Do something
    
    func doLoadMovieData(request: Detail.Movie.Request) {
        worker = DetailWorker()
        let response = Detail.Movie.Response()
        self.presenter?.presentDetailData(response: response)
        worker?.getImage(posterURL: movieViewModel.getPosterURL(), completionHandler: { image in
            self.presenter?.updateDetailImage(response: response, uiImage: image)
        })
    }
}
