//
//  DetailPresenter.swift
//  TheMovieDb
//
//  Created by Misael Chávez on 30/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic {
    func presentDetailData(response: Detail.Movie.Response)
    func updateDetailImage(response: Detail.Movie.Response, uiImage: UIImage)
}

class DetailPresenter: DetailPresentationLogic {
    weak var viewController: DetailDisplayLogic?
    
    // MARK: Do something
    
    func presentDetailData(response: Detail.Movie.Response) {
        let viewModel = Detail.Movie.ViewModel()
        viewController?.displayMovieData(viewModel: viewModel)
    }
    
    func updateDetailImage(response: Detail.Movie.Response, uiImage: UIImage) {
        let viewModel = Detail.Movie.ViewModel()
        viewController?.displayImageMovieData(viewModel: viewModel, uiImage: uiImage)
    }
}
